import discord
from discord.ext import commands
import logging
import requests
import json

logging.basicConfig(level=logging.DEBUG)
client = commands.Bot(command_prefix='./')

with open('token.json') as token_file:
    data = json.load(token_file)

TOKEN = data['token']


@client.event
async def on_ready():
    print("We have logged in as {0.user}".format(client))


@client.command()
async def avatar(ctx, member: discord.User = None):

    if member == None:
        embed = discord.Embed(
        colour = discord.Color.blue()                   
        )
        embed.set_image(url=ctx.message.author.avatar_url)
        embed.set_footer(text="requested by {}".format(ctx.message.author), icon_url=ctx.message.author.avatar_url)  
        await ctx.send(embed=embed)
    else:
        embed = discord.Embed(
        colour = discord.Color.gold()                   
        )
        embed.set_image(url=member.avatar_url)
        embed.set_footer(text="requested by {}".format(ctx.message.author), icon_url=ctx.message.author.avatar_url,)  
        await ctx.send(embed=embed)


@client.command()
async def inspiro(ctx):
    inspiro_gen = requests.get("https://inspirobot.me/api?generate=true")
    embed = discord.Embed(
       
        colour = discord.Color.green()
    )
    
    embed.set_image(url=inspiro_gen.text)
    embed.set_footer(text="Image generated by InspiroBot", icon_url="https://inspirobot.me/favicon.ico")

    await ctx.send(embed=embed)

@client.command()
@commands.has_permissions(manage_messages=True)
async def mute(ctx, member: discord.Member):
    role = discord.utils.get(member.guild.roles, name="/dev/null")
    await member.add_roles(role)
    embed=discord.Embed(description="{0} has been muted by {1}".format(member, ctx.message.author))
    embed.set_thumbnail(url=member.avatar_url)
    embed.add_field(name="**Reason:**", value="T", inline=False)

    await ctx.send(embed=embed)

@client.command()
@commands.has_permissions(manage_messages=True)
async def unmute(ctx, member: discord.Member):
    role = discord.utils.get(member.guild.roles, name="/dev/null")
    await member.remove_roles(role)
    embed=discord.Embed(description="{0} has been unmuted by {1}".format(member, ctx.message.author))
    embed.set_thumbnail(url=member.avatar_url)
    await ctx.send(embed=embed)

@client.command()
async def urban(ctx, word):
    word_request = requests.get("https://api.urbandictionary.com/v0/define?term={}".format(word))
    word_data = json.loads(word_request.text)

    embed = discord.Embed(
        title = word_data['list'][0]['word'],
        description = word_data['list'][0]['definition'],
    )
 
    embed.add_field(value=word_data['list'][0]['example'], name="**example(s)**")
    embed.set_thumbnail(url=client.user.avatar_url)
    await ctx.send(embed=embed)



    

client.run(TOKEN)