import discord
from discord.ext import commands
import requests
import json

class Misc(commands.Cog):
  def __init__(self, bot):
    self.bot = bot
      
  @commands.command()
  async def avatar(self, ctx, member: discord.User = None):
  
      if member == None:
          embed = discord.Embed(
          colour = discord.Color.blue()                   
          )
          embed.set_image(url=ctx.message.author.avatar_url)
          embed.set_footer(text="requested by {}".format(ctx.message.author), icon_url=ctx.message.author.avatar_url)  
          await ctx.send(embed=embed)
      else:
          embed = discord.Embed(
          colour = discord.Color.gold()                   
          )
          embed.set_image(url=member.avatar_url)
          embed.set_footer(text="requested by {}".format(ctx.message.author), icon_url=ctx.message.author.avatar_url,)  
          await ctx.send(embed=embed)
  
  
  @commands.command()
  async def inspiro(self, ctx):
      inspiro_gen = requests.get("https://inspirobot.me/api?generate=true")
      embed = discord.Embed(
         
          colour = discord.Color.green()
      )
      
      embed.set_image(url=inspiro_gen.text)
      embed.set_footer(text="Image generated by InspiroBot", icon_url="https://inspirobot.me/favicon.ico")
  
      await ctx.send(embed=embed)
  
  
  @commands.command()
  async def urban(self, ctx, *, word):
      word_request = requests.get("https://api.urbandictionary.com/v0/define?term={}".format(word))
      word_data = json.loads(word_request.text)
      
      
    
  
      embed = discord.Embed(
          title = word_data['list'][0]['word'],
          description = word_data['list'][0]['definition'],
      )
   
      embed.add_field(value=word_data['list'][0]['example'], name="**example(s)**")
      embed.set_thumbnail(url=discord.bot.user.avatar_url)
      await ctx.send(embed=embed)

    
    
 
    
  
    
    
    
def setup(bot):
  bot.add_cog(Misc(bot))